(global-set-key (kbd "C-?") 'help-command)
(global-set-key (kbd "M-?") 'mark-paragraph)
(global-set-key (kbd "C-h") 'delete-backward-char)
(global-set-key (kbd "M-h") 'backward-kill-word)
(require 'package)
(add-to-list 'package-archives
             '("melpa" . "http://melpa.milkbox.net/packages/") t)
(package-initialize)
(unless (package-installed-p 'scala-mode2)
  (package-refresh-contents) (package-install 'scala-mode2))
(require 'package) 
(add-to-list 'package-archives 
	     '("melpa" . "https://melpa.org/packages/") t) 
(package-initialize) 
(unless (package-installed-p 'sbt-mode) 
  (package-refresh-contents) (package-install 'sbt-mode))
